### ISSUE TITLE
invalid_read on several different shellcode

### ISSUE THREAD

**Issue by LloydLabs** [fireeye/speakeasy#43]
Really neat project thus far, just have a small issue with it. When using the `-r` flag on several different variations of shellcode (mainly from https://github.com/qilingframework/qiling/tree/master/examples/shellcodes), I keep getting `invalid_read`.  Not really sure what's going on with it, also, is there any reason the `urlmon` `LoadLibrary` call failed from below?

Example execution:
```
 python .\run_speakeasy.py -r -a x86 -t ..\win32_urldownload.bin -o report.json
0x104b: 'kernel32.LoadLibraryA("urlmon")' -> 0x0
Caught error: invalid_read
* Finished emulating
* Saving emulation report to report.json
```

**Comment by drewvis** [comment]
Hi, thanks for pointing this out. So the reason that invalid_read error occurred was because loadlibrary returned NULL in your example. The shellcode didn't perform any error checking and crashed with a NULL pointer dereference. This is because by default, speakeasy will do what it can to provide a decoy PE for shellcode to parse (based on the functions that are currently supported for emulation).

I went ahead and added support for urlmon.dll and that sample fully emulates now.

In the future you can supply a "decoy directory" with the "-l" containing real DLLs like urlmon.dll. This instructs speakeasy to load the decoy DLL when shellcode accesses it.

Hope that helps, thanks for the feedback.

**Comment by LloydLabs** [comment]
Awesome, thanks for the speedy fix @drewvis! I'll be sure to submit a PR if I come across any other APIs that are yet to be implemented 👍
