### ISSUE TITLE
How to debug unhandled_interrupt

### ISSUE THREAD

**Issue by kartone** [fireeye/speakeasy#75]
While emulating, it stuck with this message:

`0x50008: Unhandled interrupt: intnum=0x3`
`shellcode: Caught error: unhandled_interrupt`

How to understand where it's failing and eventually trying to fix it in order to continue emulation?

**Comment by drewvis** [comment]
Hi, so it looks like this may be expected behavior. Speakeasy has default handlers for what data to send back for network activity. It looks like in the example here, the shellcode was a stager that downloads additional shellcode. By default, speakeasy will provide 0xCC (int3) bytes for shellcode downloaders. This can be overridden in the configuration file. If you have access to what the shellcode expects to download, you can set this in the configuration file.

Hope this helps.

**Comment by kartone** [comment]
Oh, thank you. So, the int0x3 is provided by default. I should have read with four eyes documentation. Sorry about that.
