### ISSUE TITLE
Adding a new API hook

### ISSUE THREAD

**Issue by kartone** [fireeye/speakeasy#76]
When emulating a EXE file, I would add another API hook because of this: 

`module_entry: Caught error: unsupported_api`
`Invalid memory read (UC_ERR_READ_UNMAPPED)`
`Unsupported API: kernel32.InitializeSRWLock (ret: 0x4d41b6)`

[From MSDN,](https://docs.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-initializesrwlock) this function seems pretty simple so, for a learning experience, I would define a new API hook in the framework. Can you point me how to approach this task? I would start from the provided example `emu_exe.py` 

`void InitializeSRWLock(
  PSRWLOCK SRWLock
);`

Thanks!

**Comment by drewvis** [comment]
You can add an API handler to kernel32.py and the framework will automatically pick it up and call it. As an example, see the implementation of the AddAtom handler here: https://github.com/fireeye/speakeasy/blob/master/speakeasy/winenv/api/usermode/kernel32.py#L4380

Since we don't truly need to initialize the synchronization object in InitializeSRWLock, you can simply return, similar to what the AddAtom function is doing.

**Comment by kartone** [comment]
Will make sure to have a PR when I'm done. :) 
Thanks
